name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: kafka_lag_stats pipeline
        runs-on: ubuntu-latest
        timeout-minutes: 40
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Run backend test
              run: |
                  chmod +x mvnw
                  # ./mvnw -ntp clean verify
            - name: Analyze code
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: ./mvnw -ntp initialize sonar:sonar -Dsonar.organization=cbornet-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
              # -Dsonar.github.pullRequest="${{ github.event.pull_request.html_url }}"
            - name: Package application
              run: ./mvnw -ntp package -Pprod -DskipTests
            - name: Build and publish docker image
              if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
              run: |
                  GIT_TAG=:${GITHUB_REF#refs/tags/}
                  DOCKER_TAG=${GIT_TAG#:refs/heads/master}
                  ./mvnw -ntp jib:build -Djib.to.image=cbornet/kafka-lag-stats${DOCKER_TAG} -Djib.to.auth.username="${{ secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKER_PASSWORD }}"
